services:
  image-upload:
    build:
      context: image-upload
    expose:
      - 80
    environment:
      - BASE_PATH=image-upload/
    networks:
      - zoomed-net
  image-blog:
    build:
      context: image-blog
    environment:
      - BASE_PATH=image-blog/
    ports:
      - 8081:80
    networks:
      - zoomed-net
  nginx:
    image: nginx:1.21
    ports:
      - 8080:80
    volumes:
      - ./environment/nginx/:/etc/nginx/templates/
      - ./temp:/etc/nginx/conf.d/
    restart: unless-stopped
    environment:
      - BASE_PATH_IMAGE_UPLOAD=image-upload/
      - BASE_PATH_IMAGE_BLOG=image-blog/
    networks:
      - zoomed-net

volumes:
  temp:

    null
networks:
  zoomed-net:
    driver: bridge
